experiment:
  name: bcnn_cub 1
  log_dir: results/bcnn
  cuda: [0]
  seed: 0
dataset:
  name: mosquito
  root_dir: data/dataset_mosquito
  meta_dir: metadata/dataset_mosquito
  batch_size: 24
  num_workers: 4
  transformer:
    image_size: 224
    resize_size: 256
model:
  name: BCNN
  stage: 1  # Training stage for BCNN. Stage 1 freeze backbone parameters.
  num_classes: 3
train:
  epoch: 55
  save_frequence: 5
  optimizer:
    name: SGD
    lr: 1.0
    weight_decay: 0.00000001
    momentum: 0.9
  scheduler:
    name: ReduceLROnPlateau
  criterion:
    name: CrossEntropyLoss
