experiment:
  name: bcnn_cub 1_1
  log_dir: results/bcnn
  cuda: [0]
  seed: 0
dataset:
  name: mosquito
  root_dir: data/dataset_mosquito
  meta_dir: metadata/dataset_mosquito
  batch_size: 24
  num_workers: 4
  transformer:
    image_size: 224
    resize_size: 256
model:
  name: BCNN
  stage: 2  # Training stage for BCNN. We train all parameters in stage 2.
  load: results/bcnn/bcnn_cub 1/best_model.pth  # Load model trained in stage 1.
  num_classes: 3
train:
  epoch: 30
  save_frequence: 5
  val_first: True
  optimizer:
    name: SGD
    lr: 0.005
    weight_decay: 0.00001
    momentum: 0.9
  scheduler:
    name: ReduceLROnPlateau
  criterion:
    name: CrossEntropyLoss
