experiment:
  name: S3N 1
  log_dir: results/S3N
  cuda: [0]
  seed: 42
#  resume: results/S3N/S3N 2/checkpoint_epoch_20.pth
dataset:
  name: mosquito
  root_dir: data/dataset_mosquito
  meta_dir: metadata/dataset_mosquito
  batch_size: 16
  num_workers: 4
  transformer:
    image_size: 224
    resize_size: 256
model:
  name: S3N
  image_size: 224
  num_classes: 3
  radius: 0.12      # Radius of each sparse attention control sampling scale of the corresponding visual evidence
  radius_inv: 0.3   # Radius of complementary sparse attention.
  base_ratio: 0.09
train:
  epoch: 100
  save_frequence: 50
  optimizer:
    name: SGD
    lr: 0.005              # x0.1 for backbone
    momentum: 0.9
    weight_decay: 0.0001
  scheduler:
    name: CosineAnnealingLR
    T_max: 100
    eta_min: 0.000001
  criterion:
    name: MultiSmoothLoss
    smooth_ratio: 0.85
