experiment:
  name: APCNN
  cuda: [0]
dataset:
  name: 
  root_dir: data/LargeImage_dataset2_mosquito
  meta_dir: metadata/dataset2_mosquito
  batch_size: 24
  num_workers: 4
  transformer:
    resize_size: 512
    image_size: 448
model:
  name: APCNN
  num_classes: 3
  load: results/APCNN/AP 2/APCNN_epoch_10.pth
