experiment:
  name: API_res152_v0.1
  cuda: [0]
dataset:
  name: 
  root_dir: data/dataset_mosquito
  meta_dir: metadata/dataset_mosquito
  batch_size: 24 # Adjust
  num_workers: 4
  transformer:
    image_size: 224
    resize_size: 256
model:
  name: APINet
  num_classes: 3
  load: results/APINet/API_res152_v0.1/best_model.pth
  labels: ['aedes ', 'anopheles ', 'culex']
