experiment:
  name: APCNN
  cuda: [0]
dataset:
  name: 
  root_dir: data/dataset_mosquito
  meta_dir: metadata/dataset_mosquito
  batch_size: 24
  num_workers: 4
  transformer:
    resize_size: 256
    image_size: 224
model:
  name: APCNN
  num_classes: 3
  load: results/APCNN/AP 1/APCNN_epoch_100.pth
